### ISSUE TITLE
Feature - Activity Indicator

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#24]
**Is your feature request related to a problem? Please describe.**
As accused at the [1st Acceptance Test](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project-quality-management/acceptance-tests/1st-test/), the user has no feedback to tell him/her if the app is working properly.

**Describe the solution you'd like**
A simple way of giving to the user some feedback is putting an **activity indicator**, which will be loaded on the badge's place while the results are not received.

**Describe alternatives you've considered**
Another great solution, even better, is to render a progress bar indicating how much of the total already was calculated. Even if this is a better option, the complexity of implementation is beyond we can offer for now. Let's just try simple solutions.

**Additional context**
Any more context can be obtained at the [1st Acceptance Test Report](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project-quality-management/acceptance-tests/1st-test/)

**Comment by VitorMeirelesOliveira** [comment]
When I was open a pull request I've noticed something quite annoying, when I go to a repository(or open a pull request situation, for example) the loading bar keeps running outside the code tab, maybe that's not the expected response and behavior because there are no badges over there, as you can see at the screenshot under.

![image](https://user-images.githubusercontent.com/37275710/57994018-a21a7400-7a91-11e9-8a10-de8528ac0df1.png)

**Comment by filipetoyoshima** [comment]
#37 may solve this problem
