### ISSUE TITLE
Feature - Login interface

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#38]
### **Is your feature request related to a problem? Please describe.**
[GitHub API](https://developer.github.com/v3/previews/) requires an `username` and a `token` to require the amount of data we need. To be fair with users, they must use their own tokens.

### **Describe the solution you'd like**
The GitHub API provides a [guide to authenticate](https://developer.github.com/v3/guides/basics-of-authentication/). It is necessary to study this and, then, decide the way we are authenticating the user. Probably, it will be a button on add-on's Popup called "Login" which go to the GitHub default authentication page that will provide us the needed data.

### **Describe alternatives you've considered**
Another way of doing some "authentication" is just placing input fields to the user manually insert his/her username and token. **It is NOT a safe solution**. We're dealing with critical data and the user's token can't be treated like this.

### Acceptance Criteria
- [x] Study GitHub API auth. **Found info must be commented here**
- [x] WIP - The other criteria must be decided after some study.

**Comment by cjjcastro** [comment]
The [github api provides a way to authenticate](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/) using two URLs, the first returns a code that is used to request the access token at the second URL.

https://github.com/login/oauth/authorize?response_type=code&client_id=${client_id}

https://github.com/login/oauth/access_token?client_id=${client_id}&client_secret=${client_secret}&code=${code}

My idea is to insert the first URL as the action of some button in the popup and insert the second in the contentscript, because the return of the first is returned to a specific URL.

**Comment by cjjcastro** [comment]
the username is not necessary to make the request, only the access token is sufficient.
