### ISSUE TITLE
Feature - Tooltips on commit graphs

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#45]
## **Is your feature request related to a problem? Please describe.**
The idea of #42 is to give a visual idea of the data used - the commits. But the graph still giving not so much information, cause I can't know exactly how many commits were done in a certain week.

## **Describe the solution you'd like**
A Tooltip / Hover on the graph that shows the exact number of commits in each spot of the graph.

## **Acceptance Criteria**
- [x] Show the number of commits in each point of the graph when the cursor passes over it.

**Comment by FranciscoHeronildo** [comment]
The tooltip has been added but is not yet returning the type of value that is expected. Because it shows the values in the total area of the graph. In this way, as you move the mouse over points, it shows values of type float.

![tooltip11](https://user-images.githubusercontent.com/30841230/58446037-83416080-80d5-11e9-90cd-b6bb2ef759e2.png)

**Comment by vitorAlves7** [comment]
We are thinking of using the toolbox function because it shows the exact value of the point

**Comment by vitorAlves7** [comment]
The previously reported problem has been solved, we have changed the value of the trigger attribute of the tooltip. so it shows the exact value of the point, follows the example image.

![Captura de tela de 2019-05-28 00-05-12](https://user-images.githubusercontent.com/43835325/58447987-ba674000-80dc-11e9-94df-76e69df9dfd1.png)
